services:
  postizmcp:
    image: oculair/postiz-mcp:latest
    ports:
      - 3084:3084
    restart: unless-stopped
    environment:
      PORT: 3084
      POSTIZ_API_URL: https://postiz.oculair.ca/api
      POSTIZ_API_KEY: 255364482e25a51ff9a6660135b8c88995e7ae68615fb9a67ad14d601f8fe0ff
      NODE_ENV: ${NODE_ENV:-production}
networks: {}
